MyTact={}
MyTact[0]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_NEVER,CAST_REACT,PUSH_SELF,DEBUFF_ANY_C,CLASS_BOTH,RESCUE_ALL,-1,SNIPE_OK,KS_POLITE,1,CHASE_NORMAL} --Default
TactLastSavedDate        = "01/30/2019 7:04:59 AM"