MyTact={}
MyTact[0]={TACT_ATTACK_H,SKILL_ALWAYS,KITE_NEVER,CAST_REACT,PUSH_SELF,DEBUFF_ANY_C,CLASS_BOTH,RESCUE_ALL,-1,SNIPE_OK,KS_POLITE,1,CHASE_NORMAL} --Default
TactLastSavedDate        = "01/31/2019 11:33:29 PM"